
platform :ios do
  desc 'configures the background color of the application, along with the welcome message'
  lane :customize_build do |options|
    require_relative 'ios_customize_build'
    customize_build(options)
  end

  desc 'customize and build the iOS application'
  lane :build_custom_app do |options|
    require_relative 'ios_build_custom_app'
    build_custom_app(options)
  end

  desc 'download the latest released app for iOS'
  lane :download_latest_release do |options|
    require_relative 'x_download_latest_release'
    download_latest_release(options)
  end

  desc 'download, customize, and sign the app according to customer\'s needs'
  lane :customize_built_app do |options|
    require_relative 'ios_customize_built_app'
    customize_built_app(options)
  end
end

platform :android do
  lane :customize_build do |options|
    require_relative 'android_customize_build'
    customize_build(options)
  end

  lane :build_custom_app do |options|
    require_relative 'android_build_custom_app'
    build_custom_app(options)
  end

  lane :download_latest_release do |options|
    require_relative 'x_download_latest_release'
    download_latest_release(options)
  end

  lane :customize_built_app do |options|
    require_relative 'android_customize_built_app'
    customize_built_app(options)
  end
end
