name: Issue Events
on:
  issues:
    types: [labeled]

jobs:
  process_mobile_build_request:
    if: github.event.issue.state == 'open' && github.event.label.name == 'mobile-build-requested'
    runs-on: ubuntu-latest
    steps:
      - run: echo "label changed for ${{ github.event.issue.html_url }}"
      - run: echo "github ${{ toJSON(github) }}"
