name: Issue Events
on:
  issues:
    types: [labeled]

jobs:
  process_mobile_build_request:
    runs-on: ubuntu-latest
    steps:
      - run: echo "label changed for ${{ github.event.issue.html_url }}"
